### ISSUE TITLE
GPU machines can be in a bad state

### ISSUE THREAD

**Issue by osrf-migration** [osrf/cloudsim-legacy#10]
**Original report ([archived issue](https://osrf-migration.github.io/osrf-archived-gh-pages/#!/osrf/cloudsim-legacy/issues/10)) by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

The original report had attachments: [log-goodstate.tgz](https://osrf-migration.github.io/osrf-archived-gh-pages/data/repositories/osrf/cloudsim-legacy/issues/10/attachments/log-goodstate.tgz)

----------------------------------------
Sometimes, it seems that a GPU-equipped machine boots up in a bad state, wherein GL applications run badly or not at all.  Symptoms include:

 * glxgears returns wildly varying frame rates
 * gzserver never completes its setup, getting stuck in the first call that it makes to GL

Rebooting the machine seems to fix it.

I'm attaching a tarball of /var/log from a machine that was in the bad state then was rebooted into the good state (the logs were grabbed when in the good state).  We should do the same (get logs) for a machine in the bad state.

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------

* Edited issue description

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Here's a backtrace across all threads of `gzserver` compiled in Debug mode from `gazebo_1.3`, when it was stuck during startup because the machine was in the bad state:

    Thread 4 (Thread 0x7fffe51ed700 (LWP 10771)):
    #0  0x00007ffff6bb552d in nanosleep () from /lib/x86_64-linux-gnu/libpthread.so.0
    #1  0x00007ffff7bb4dbd in gazebo::common::Time::MSleep(unsigned int) () from /usr/lib/libgazebo_common.so.1
    #2  0x000000000042e39d in gazebo::Master::Run() ()
    #3  0x00007ffff64a6ce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
    #4  0x00007ffff6bade9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #5  0x00007ffff584fcbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
    #6  0x0000000000000000 in ?? ()
 
    Thread 3 (Thread 0x7fffe6006700 (LWP 10770)):
    #0  0x00007ffff5850353 in epoll_wait () from /lib/x86_64-linux-gnu/libc.so.6
    #1  0x00007ffff76546b4 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) () from /usr/lib/libgazebo_transport.so.1
    #2  0x00007ffff7654e3e in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /usr/lib/libgazebo_transport.so.1
    #3  0x00007ffff7655435 in boost::asio::io_service::run() () from /usr/lib/libgazebo_transport.so.1
    #4  0x00007ffff64a6ce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
    #5  0x00007ffff6bade9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #6  0x00007ffff584fcbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
    #7  0x0000000000000000 in ?? ()
 
    Thread 2 (Thread 0x7fffe6807700 (LWP 10769)):
    #0  0x00007ffff6bb1d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
    #1  0x00007ffff7b9e7d9 in gazebo::common::ModelDatabase::UpdateModelCache() () from /usr/lib/libgazebo_common.so.1
    #2  0x00007ffff64a6ce9 in thread_proxy () from /usr/lib/libboost_thread.so.1.46.1
    #3  0x00007ffff6bade9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
    #4  0x00007ffff584fcbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
    #5  0x0000000000000000 in ?? ()
 
    Thread 1 (Thread 0x7ffff7fb5840 (LWP 10766)):
    #0  0x00007fffeef55419 in ?? () from /usr/lib/nvidia-current/libGL.so.1
    #1  0x00007fffeef55443 in ?? () from /usr/lib/nvidia-current/libGL.so.1
    #2  0x00007fffeae86988 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #3  0x00007fffeae86aeb in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #4  0x00007fffeae24f3d in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #5  0x00007fffeadf9b7f in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #6  0x00007fffeadf9f35 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #7  0x00007fffeae06c01 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #8  0x00007fffeae06e88 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #9  0x00007fffeadb09a9 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #10 0x00007fffead91e60 in ?? () from /usr/lib/nvidia-current/libnvidia-glcore.so.295.40
    #11 0x00007fffeef2dde0 in ?? () from /usr/lib/nvidia-current/libGL.so.1
    #12 0x00007fffeef2df40 in ?? () from /usr/lib/nvidia-current/libGL.so.1
    #13 0x00007fffeef35500 in ?? () from /usr/lib/nvidia-current/libGL.so.1
    #14 0x00007ffff368cb66 in gazebo::rendering::RenderEngine::CreateContext() () from /usr/lib/libgazebo_rendering.so.1
    #15 0x00007ffff3690043 in gazebo::rendering::RenderEngine::Load() () from /usr/lib/libgazebo_rendering.so.1
    #16 0x00007ffff36961e9 in gazebo::rendering::load() () from /usr/lib/libgazebo_rendering.so.1
    #17 0x0000000000421278 in gazebo::Server::LoadImpl(boost::shared_ptr<sdf::Element>) ()
    #18 0x0000000000422038 in gazebo::Server::LoadFile(std::string const&) ()
    #19 0x000000000042303f in gazebo::Server::ParseArgs(int, char**) ()
    #20 0x000000000041d85d in main ()

**Comment by osrf-migration** [comment]
**Original comment by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------
I think I've seen something suspiciously similar on my laptop with some of the older precise linux kernels, it's possible 3.2.0-25 was one of them, maybe worth a try updating to newer kernels to see if this is fixed?

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
Upgrading the kernel seems worth a try.  Perhaps use the [procedure](http://gazebosim.org/wiki/DRC/DRCKickoffLaptops#Upgrade_the_kernel) that we did for the kickoff laptops.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
Here's something that's allowed me to recover a machine that was in a bad state:

```
#!python
sudo service lightdm restart

```

Let me know if fails for you, as this is my best lead so far.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
The 
```
#!python

sudo service lightdm restart
```
appears to be a red herring.

I have found another machine in bad state. After a reboot, I was able to run atlas simulations at about 0.6 realtime, and I let it run overnight. 

Running 
```
#!python

time glx_info
```
would give times of either 1.5 secs (as expected) or 20secs (too slow).  90% of the tiem I would get bad results. glzxgears would give fps of 0.1 for a minute or two, but those would pick up after a minute or so (1700+).

After another reboot of the same machine, I get glsinfo running within 4.5 sec consistently with good simulations.

Conclusion: Rebooting helps, problems don't seem to "come back" once the machine is in a good state.

To be continued...

**Comment by osrf-migration** [comment]
**Original comment by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------

* changed state from "new" to "wontfix"

With the switch to SoftLayer for the VRC, this issue is no longer relevant.  Until we hear from non-/post-VRC users who encounter this issue on AWS machines, we won't work on it.
