### ISSUE TITLE
AWS reports instance as missing

### ISSUE THREAD

**Issue by osrf-migration** [osrf/cloudsim-legacy#19]
**Original report ([archived issue](https://osrf-migration.github.io/osrf-archived-gh-pages/#!/osrf/cloudsim-legacy/issues/19)) by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

The original report had attachments: [EC2 Management Console - Chromium_005.png](https://osrf-migration.github.io/osrf-archived-gh-pages/data/repositories/osrf/cloudsim-legacy/issues/19/attachments/EC2_Management_Console_-_Chromium_005.png)

----------------------------------------
This error happened while trying to set the tags on the field computer: AWS reported the instance to be inexistent. The instance does exist, however (see image), and this it the first report of such a problem.

LOG: cloudsimd.py launch error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-ec9bf39c' does not exist</Message></Error></Errors><RequestID>c77fc68d-506d-4281-b896-0939ac40f6f7</RequestID></Response>
LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 111, in launch
    launch(username, constellation_name, tags, credentials_ec2, constellation_directory)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 137, in launch
    CONFIGURATION)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 612, in trio_launch
    ec2conn.create_tags([ robot_aws_id ], robot_tags)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 3203, in create_tags
    return self.get_status('CreateTags', params, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1019, in get_status
    raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-ec9bf39c' does not exist</Message></Error></Errors><RequestID>c77fc68d-506d-4281-b896-0939ac40f6f7</RequestID></Response>

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
Issue #54 was marked as a duplicate of this issue.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------

* changed state from "new" to "wontfix"
