### ISSUE TITLE
timeout on creation of cloudsim

### ISSUE THREAD

**Issue by osrf-migration** [osrf/cloudsim-legacy#54]
**Original report ([archived issue](https://osrf-migration.github.io/osrf-archived-gh-pages/#!/osrf/cloudsim-legacy/issues/54)) by Brian Gerkey (Bitbucket: [Brian Gerkey](https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/), GitHub: [gerkey](https://github.com/gerkey)).**

----------------------------------------
I had the following error when trying to launch a new CloudSim machine, using cloudsim-1.2.0 (private details removed from command line):

    $ ./cloudsim-1.2.0/bin/create_cloudsim.py <address> <key> <secret-key> <zone>
    ./cloudsim-1.2.0/inside/cgi-bin
    ./cloudsim-1.2.0/cloudsimd/launchers
    ./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py
    Traceback (most recent call last):
      File "./cloudsim-1.2.0/bin/create_cloudsim.py", line 51, in <module>
        machine = cloudsim.cloudsim_bootstrap(username, tmp_fname.name)
      File "./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py", line 446, in cloudsim_bootstrap
      File "./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py", line 249, in launch
launch_utils.launch.LaunchException: timeout while waiting for EC2 machine(s) cloudsim_c6b04475a

It looks like, from the AWS Console, that the machine was created, but never received any tags or other provisioning.

I tried the same command again, about 30 minutes later (after trying to debug the failed launch), and it succeeded.

Perhaps a timeout should be adjusted.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------

* changed state from "new" to "duplicate"

Duplicate of #19.
