### ISSUE TITLE
The security group 'teamlogin' does not exist

### ISSUE THREAD

**Issue by osrf-migration** [osrf/cloudsim-legacy#6]
**Original report ([archived issue](https://osrf-migration.github.io/osrf-archived-gh-pages/#!/osrf/cloudsim-legacy/issues/6)) by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
The security group 'teamlogin' does not exist. Note in the post below, I removed my email, key and secret_key. How can I resolve this? Thanks.

mighty@itauma:~/Projects/cloudsim-1.0.0$ ./bin/create_cloudsim.py myemail@gmail.com mykey mysecret_key
./inside/cgi-bin
./cloudsimd/launchers
./cloudsimd/launchers/cloudsim.pyc
Warning: redis not installed.
cloudsim log> cloudsim launch constellation 'b592a288-4298-11e2-b2c3-0025d3644a10'
event: cloudsim
data:{'state': 'reserve', 'machine_name': 'cloudsim_b592a288-4298-11e2-b2c3-0025d3644a10', 'type:': 'launch'}

Traceback (most recent call last):
  File "./bin/create_cloudsim.py", line 51, in <module>
    machine = cloudsim.cloudsim_bootstrap(username, tmp_fname.name)
  File "./cloudsimd/launchers/cloudsim.py", line 223, in cloudsim_bootstrap
  File "./cloudsimd/launchers/cloudsim.py", line 133, in launch
  File "./inside/cgi-bin/common/machine.py", line 124, in __init__
  File "./inside/cgi-bin/common/machine.py", line 170, in _launch
  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 670, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 916, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'teamlogin' does not exist</Message></Error></Errors><RequestID>b32b9e4b-7934-486e-bd9d-e085eb5c2636</RequestID></Response>

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------

* changed state from "new" to "resolved"

Fixed in 1.0.1

**Comment by osrf-migration** [comment]
**Original comment by amightyo (Bitbucket: [amightyo](https://bitbucket.org/%7B610d5b61-4114-4f41-b912-3c7c2de2bb28%7D/)).**

----------------------------------------
Oh Great! I'm logged in. Thanks Hugo
