### ISSUE TITLE
Console doesn't display constellation anymore

### ISSUE THREAD

**Issue by osrf-migration** [osrf/cloudsim-legacy#60]
**Original report ([archived issue](https://osrf-migration.github.io/osrf-archived-gh-pages/#!/osrf/cloudsim-legacy/issues/60)) by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

The original report had attachments: [Screenshot from 2013-03-10 14:11:23.png](https://osrf-migration.github.io/osrf-archived-gh-pages/data/repositories/osrf/cloudsim-legacy/issues/60/attachments/Screenshot_from_2013-03-10_141123.png), [Screenshot from 2013-03-10 14:35:47.png](https://osrf-migration.github.io/osrf-archived-gh-pages/data/repositories/osrf/cloudsim-legacy/issues/60/attachments/Screenshot_from_2013-03-10_143547.png), [cloudsimconsole1.3.png](https://osrf-migration.github.io/osrf-archived-gh-pages/data/repositories/osrf/cloudsim-legacy/issues/60/attachments/cloudsimconsole1.3.png)

----------------------------------------
The console was displaying all the machines of the constellation. It doesn't work anymore.
See attached picture.

**Comment by osrf-migration** [comment]
**Original comment by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

----------------------------------------

* set attachment to "Screenshot from 2013-03-10 14:35:47.png"

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
The CloudSim machine's database is corrupt or it does not contain any information about the constellation cxe378f80a. 

Please verify that constellation cxe378f80a was created from that CloudSim instance (54.242.249.62). This should be the case, since things were working before.

The next thing to do is to log in the CloudSim instance. You will need the ssh keys available via the "ssh key download" link at the top right corner of CloudSim (you must be logged in with admin privileges).

Once in the CloudSim instance, use the root account (sudo su) to look for the following directory:


```
#!python

/var/www-cloudsim-auth/machines/cxe378f80a
```

You should be able to find the keys to your machines there.

Then, look for


```
#!python

/tmp/cloudsimd.log
```

This could give a clue to what may have happened. Can you send the content?

You can also stop and start the daemon by running:


```
#!python

sudo stop cloudsimd

and

sudo start cloudsimd

```

Its important to note that you don't need CloudSim to use the constellation machines. However, what you are experiencing is not normal and we should find the cause for this problem. Next steps could involve adding an osrf user to the admin list.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------
Another thing to try is to point your browser to 


```
#!python

54.242.249.62/cloudsim/inside/cgi-bin/constellations/cxe378f80a
```

This should give you an idea of what is the database for that constellation. It is the REST url to access constellation information. You need to be logged with the browser in order to get useful information.

**Comment by osrf-migration** [comment]
**Original comment by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

----------------------------------------
Hi Hugo
1. That's the output of /var/www-cloudsim-auth/machines:

```
#!script

michele@darpaws5:~/trio/cloudsim_c4097d37e$ ./ssh2.bash 
Warning: Permanently added '54.242.249.62' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 12.04.1 LTS (GNU/Linux 3.2.0-29-virtual x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Mar 13 05:14:12 UTC 2013

  System load:  0.08              Processes:           68
  Usage of /:   15.9% of 7.97GB   Users logged in:     0
  Memory usage: 37%               IP address for eth0: 10.193.39.129
  Swap usage:   0%

  => There is 1 zombie process.

  Graph this data and manage this system at https://landscape.canonical.com/

101 packages can be updated.
46 updates are security updates.

Get cloud support with Ubuntu Advantage Cloud Guest
  http://www.ubuntu.com/business/services/cloud
*** /dev/xvda1 will be checked for errors at next reboot ***

ubuntu@domU-12-31-39-0F-24-73:~$ ls -l /var/www-cloudsim-auth/machines/cxe378f80a
ls: cannot access /var/www-cloudsim-auth/machines/cxe378f80a: Permission denied
ubuntu@domU-12-31-39-0F-24-73:~$ sudo su !$
sudo su /var/www-cloudsim-auth/machines/cxe378f80a
Unknown id: /var/www-cloudsim-auth/machines/cxe378f80a

```

I have no way to ftp a file but the last lines of /tmp/cloudsimd.log are:


```
#!script

cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2016ms
pipe 3

LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2016ms
pipe 3


cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 1999ms
pipe 3
LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 1999ms
pipe 3


cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2016ms
pipe 3

LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable
--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2016ms
pipe 3


cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2015ms
pipe 3

LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2015ms
pipe 3


cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2000ms
pipe 3

LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2000ms
pipe 3


cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unrea

```

Note that there is no date and time to this log  but I stopped the simulator and the field computers one hour ago. However, the router  (10.0.0.50) is always on since the first launch (as well as the cloudsim instance).

**Comment by osrf-migration** [comment]
**Original comment by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

----------------------------------------
I am a bit afraid to stop the simulation and not to be able to start it again.
We are using the constellation without the console but the console helps ....

Note that entering with 54.242.249.62/cloudsim/inside/cgi-bin/constellations/cxe378f80a didn't help either. Same results.

I can give you access to the constellation, I want very much to be able to correct the situation. 
Thanks

**Comment by osrf-migration** [comment]
**Original comment by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

----------------------------------------
That's the beginning of the log:


```
#!script

OG: Cloudsim daemon started pid 735
LOG: args: ['/var/cloudsimd/cloudsimd.py']
LOG: async_tick_monitor [5 secs]
LOG: resume_monitoring
LOG: existing constellations [('gmail.com', 'cxe378f80a')]
LOG:    constellation gmail.com/cxe378f80a
LOG:       config vpc_trio
LOG:       state running
LOG: cloudsimd async_monitor [config vpc_trio] integrator.iai@gmail.com/cxe378f80a
LOG: monitoring [vpc_trio] integrator.iai@gmail.com/cxe378f80a from proc 'Process-2'
cloudsim log> ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /var/www-cloudsim-auth/machines/cxe378f80a/key-router-cxe378f80a.pem ubuntu@107.23.122.115 ping -c3 10.0.0.52
LOG: cloudsimd.py monitor error: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable

--- 10.0.0.52 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2014ms
pipe 3

LOG: traceback:  Traceback (most recent call last):
  File "/var/cloudsimd/cloudsimd.py", line 192, in monitor
    done = monitor(username, constellation_name, credentials_ec2, counter)
  File "/var/cloudsimd/launchers/vpc_trio.py", line 152, in monitor
    m =_monitor(username, constellation_name, credentials_ec2, counter, "vpc_trio")
  File "/var/cloudsimd/launchers/vpc_trio.py", line 268, in _monitor
    ping_robot = ssh_router.cmd("ping -c3 %s" % ROBOT_IP)
  File "/var/cloudsimd/launchers/launch_utils/sshclient.py", line 51, in cmd
    raise SshClientException(out + err)
SshClientException: PING 10.0.0.52 (10.0.0.52) 56(84) bytes of data.
From 10.0.0.50 icmp_seq=1 Destination Host Unreachable
From 10.0.0.50 icmp_seq=2 Destination Host Unreachable
From 10.0.0.50 icmp_seq=3 Destination Host Unreachable


```

**Comment by osrf-migration** [comment]
**Original comment by michele hallak (Bitbucket: [mhallak](https://bitbucket.org/%7Bf8cca72b-2f8a-4372-bcb5-10ea801a3fe9%7D/)).**

----------------------------------------

* set attachment to "cloudsimconsole1.3.png"

Today I launched a new constellation with cloudsim 1.3
That's what I have 12 hours later.

**Comment by osrf-migration** [comment]
**Original comment by Hugo Boyer (Bitbucket: [hugomatic](https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/), GitHub: [hugomatic](https://github.com/hugomatic)).**

----------------------------------------

* changed state from "new" to "on hold"
